/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.monitorfiscal.telas;

/**
 *
 * @author marcosbras
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        itfBemVindo = new javax.swing.JInternalFrame();
        pnlInterno = new javax.swing.JPanel();
        btnFechar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuConfiguracoes = new javax.swing.JMenu();
        mnuMonitor = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuApresentacao = new javax.swing.JMenuItem();
        jMeSair = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/monitorfiscal/imagens/light-effect-752761_1920.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        itfBemVindo.setTitle("Apresentação do Sistema");
        itfBemVindo.setVisible(true);
        itfBemVindo.getContentPane().setLayout(null);

        pnlInterno.setLayout(null);

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });
        pnlInterno.add(btnFechar);
        btnFechar.setBounds(480, 540, 134, 23);

        itfBemVindo.getContentPane().add(pnlInterno);
        pnlInterno.setBounds(0, 0, 620, 570);

        mnuConfiguracoes.setText("Configurações");

        mnuMonitor.setText("Monitor");
        mnuMonitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMonitorActionPerformed(evt);
            }
        });
        mnuConfiguracoes.add(mnuMonitor);

        jMenuBar1.add(mnuConfiguracoes);

        jMenu2.setText("Sobre");

        mnuApresentacao.setText("Apresentação");
        mnuApresentacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuApresentacaoActionPerformed(evt);
            }
        });
        jMenu2.add(mnuApresentacao);

        jMenuBar1.add(jMenu2);

        jMeSair.setText("Sistema");
        jMeSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMeSairActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMeSair.add(jMenuItem1);

        jMenuBar1.add(jMeSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itfBemVindo))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itfBemVindo))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        itfBemVindo.getAccessibleContext().setAccessibleName("apresentacao");

        setSize(new java.awt.Dimension(816, 659));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuMonitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMonitorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuMonitorActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        itfBemVindo.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void jMeSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMeSairActionPerformed
       
    }//GEN-LAST:event_jMeSairActionPerformed

    private void mnuApresentacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuApresentacaoActionPerformed
        FrmPrincipal principal = new FrmPrincipal();
        principal.setVisible(true);
        dispose();
    }//GEN-LAST:event_mnuApresentacaoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JInternalFrame itfBemVindo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMeSair;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem mnuApresentacao;
    private javax.swing.JMenu mnuConfiguracoes;
    private javax.swing.JMenuItem mnuMonitor;
    private javax.swing.JPanel pnlInterno;
    // End of variables declaration//GEN-END:variables
}
