/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classes;

import java.awt.Font;

/**
 *
 * @author marcosbras
 */
public class TelaAdvinha extends javax.swing.JFrame {

    /**
     * Creates new form TelaAdvinha
     */
    public TelaAdvinha() {
        initComponents();
        lblResultado.setText("");
        lblNumeroPensado.setText("");
        lblFrase.setText("<html>O gênio está pensado em um número entre 1 e 5, em qual valor ele está pensando no momento?</html>");
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        lblFrase = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblNumeroPensado = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();
        txtValor = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/genio saindo da lampadal.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 230, -1, -1));

        lblFrase.setText("lblFrase");
        getContentPane().add(lblFrase, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 560, 330, 40));

        jButton1.setText("Enviar resposta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 620, 210, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/thought-bubble-305053_640.png"))); // NOI18N
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 650, 370));

        lblNumeroPensado.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblNumeroPensado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumeroPensado.setText("lblNumeroPensado");
        getContentPane().add(lblNumeroPensado, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 390, 190));

        lblResultado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblResultado.setForeground(new java.awt.Color(255, 0, 0));
        lblResultado.setText("lblResultado");
        lblResultado.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 310, 120));

        txtValor.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 620, 50, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int iMaximo = 5;
        int iMinimo = 1;
        
       int numeroGerado = (int) (iMinimo + Math.random() * (iMaximo - iMinimo)  );
       
       
       int numeroUsuario = Integer.parseInt(txtValor.getValue().toString());
       
       boolean bResultado = (numeroGerado == numeroUsuario)?true:false;
       
       String  sResultado = (bResultado)?"<html>Parabéns, vc acertou!</html>":"<html>Sinto muito, vc errou, tente novamente!</html>";
       
       
       lblNumeroPensado.setText(Integer.toString(numeroGerado));
       lblResultado.setText(sResultado);
       
       lblResultado.setFont(new Font("Arial Black",Font.PLAIN,18));
       
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdvinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdvinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdvinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdvinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAdvinha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblFrase;
    private javax.swing.JLabel lblNumeroPensado;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JSpinner txtValor;
    // End of variables declaration//GEN-END:variables
}
